# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Annie Hedgpeth"
description: > # this means to ignore newlines until "email:"
    Test Infrastructure Engineer committed to growth and community

email: annie.hedgpeth@gmail.com
#blog logo
logo: "/assets/images/ah_logo.jpg"
# blog cover
cover: "/assets/images/annie_and_michael.jpg"
bottom: "/assets/images/footer.jpg"

name: 'Annie Hedgpeth'
author: 'Annie Hedgpeth'
author_image: "/assets/images/AnnieHedgpeth.jpg"
permalink: /:title
paginate:	10

url: "http://www.anniehedgie.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@anniehedgie'

#fill in disqus shortname to use disqus
#disqus: anniehedgie

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/anniehedgie
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/anniehedgpeth
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/annie-hedgpeth-203393112
    desc:	Connect with me on linkedin
    share_url: https://www.linkedin.com/shareArticle
    share_title: ?title=
    share_link: "&amp;url="

# Google services
google_analytics: UA-77245607-1

excerpt_separator: <!--more-->
